steps:
  # Step 1: Build full app using the root Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/yqpay', '.']

  # Step 2: Push the built image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/yqpay']

  # Step 3: Deploy to Cloud Run (single service)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'yqpay',
        '--image', 'gcr.io/$PROJECT_ID/yqpay',
        '--region', 'asia-south1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/yqpay'
